title: BIM Roadmap
email: dalbert@onuma.com
description: > # this means to ignore newlines until "baseurl:"
  BIM Roadmap to be developed as a team through Github
#baseurl: "/BIM"
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://thomas-dalbert.github.io"
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: thomasdalbert
github_username:  thomas-dalbert

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
